#!/bin/bash
#SBATCH -J isicle_nmr
#SBATCH -N 1
#SBATCH -t 72:00:00
#SBATCH -n 1
#SBATCH -p shared

source /etc/bashrc
module purge
module load intel/18.0.0
module load gcc/8.1.0
#module load java/1.8.0_31
# python
module load python/miniconda3.7
source /share/apps/python/miniconda3.7/etc/profile.d/conda.sh
conda activate isicle

nextflow run isicle_nmr_workflow.nf -dsl2

