# {% set data = load_setup_py_data(setup_file="../setup.py",
#                                  from_recipe_dir=True) %}
context:
  version: "2.0.0"

package:
  name: isicle
  version: ${{ version }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - bioconda
    - smcolby # [linux64]
    - anaconda

build:
  number: 0
  script:
    - python -m pip install -vv --no-deps .

requirements:
  host:
    - pip
    - python
  run:
    - crest >=2.12
    - joblib
    - mobcal-shm # [linux64]
    - numpy >=1.19.4
    - nwchem >=7.0.2
    - openbabel >=3.0.0
    - openmpi
    - pandas >=1.1.4
    - python >=3.9
    - rdkit >=2023.09.1
    - snakemake >=6.3.0
    - statsmodels >=0.11.1
    - xtb >=6.5.1
