context:
  version: "2.0.0" # TODO: obtain this from package directly

package:
  name: isicle
  version: ${{ version }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - bioconda
    - smcolby
    - anaconda

build:
  number: 0
  script:
    - python -m pip install -vv --no-deps .

requirements:
  host:
    - pip
    - python
  run:
    - crest >=2.12
    - joblib
    - if: linux
      then: mobcal-shm
    - numpy >=1.19.4
    - nwchem >=7.0.2
    - openbabel >=3.0.0
    - openmpi
    - pandas >=1.1.4
    - python >=3.9
    - rdkit >=2023.09.1
    - snakemake >=6.3.0
    - statsmodels >=0.11.1
    - xtb >=6.5.1
